package com.example.rideboard.buffer

import com.example.rideboard.utils.SpatialCoordinates

data class GpsSample(
    val timestamp: Long,
    var latitude: Double,
    var longitude: Double,
    val accuracy: Float,
    var altitudeGps: Double? = null,
    var altitudeAccuracy: Float? = null,
    val speedGps: Float?,
    val speedAccuracy: Float?,
    var altitudeSrtm: Double? = null,
    var altitudeIgn: Double? = null,
    var altitudeLidarHdMnt: Double? = null,
    var altitudeLidarHdMns: Double? = null,

    var gpsPointSpeed :Double = 0.0,
    var gpsPointAcceleration :Double = 0.0,
    var gpsPointVerticalSpeed :Double = 0.0,
    var gpsPointMaxVerticalSpeed :Double = 0.0,
    var gpsPointMinVerticalSpeed :Double = 0.0,
    var gpsPointDirection: Double? = null,
    var gpsPointAltitude: Double? = null,
    var gpsPointLatitude: Double? = null,
    var gpsPointLongitude: Double? = null,
    var gpsPointGpsAltitudeAccuracy: Double = 299.9,
    var gpsPointAltitudeSourceMntMnsOrGps: String = "",
    var gpsPointSpreadAltitudeAndAltitudeGps: Double? = null,
    var gpsPointCoefficientOfSpreadAltitudeAndAltitudeGps: Double = 0.0,
    var gpsPointDurationAltitudeNotMnt: Int = 0,
    var gpsPointIsMoving: Boolean = false,
    var gpsPointIsStarted: Boolean = false,
    var gpsPointCumulatedGpsPrecision: Double = 0.0,
    var gpsPointIsAltitudeGot: Boolean = false,
    var gpsPointIsGpsAltitudeGot: Boolean = false,
    var gpsPointUncorrectedGpsAltitude: Double? = null,
    var gpsPointDisplayedVerticalSpeed: Double = 0.0,
    var gpsPointDisplayedVerticalSpeed2: Double = 0.0,
    var gpsPointDisplayedAltitude:Double? = null,
    var gpsPointDisplayedSpeed:Double = 0.0,
    var gpsPointDurationHighSpreadAltitude: Int = 0,
    var gpsPointLastDifferentSrtm : SpatialCoordinates? = null,
    var gpsPointLastDifferentLidarMnt : SpatialCoordinates? = null,
    var gpsPointLastDifferentLidarMns : SpatialCoordinates? = null,
    var gpsPointLastDifferentIgn : SpatialCoordinates? = null,
    var gpsPointDurationTime : Long = 0,
    var gpsPointTotalDistance : Double = 0.0,
    var gpsPointMaxSpeed: Double = 0.0,
    var gpsPointMaxSlope: Double = 0.0,
    var gpsPointMinSlope: Double = 0.0,
    var gpsPointSlope: Double = 0.0,
    var gpsPointMaxAltitude: Double? = null,
    var gpsPointMinAltitude: Double? = null,
    var gpsPointElevationGain: Double = 0.0,
    var gpsPointAltForElevationGain: Double? = null,
    var gpsPointStringToReset: String = "",
    var partialElevationGain: Double = 0.0,
    var partialDurationTime: Long = 0,
    var partialDistance: Double = 0.0,
    var partialDurationTimeForAverageSpeed: Long = 0,
    var partialDistanceForAverageSpeed: Double = 0.0,
    var screenVerticalSpeed4: Double = 0.0,
    var screenVerticalSpeed15: Double = 0.0,
    var screenVerticalSpeed125: Double = 0.0,
    var screenVerticalSpeed1000: Double = 0.0,
    var maxVerticalSpeed15: Double = 0.0,
    var maxVerticalSpeed125: Double = 0.0,
    var maxVerticalSpeed1000: Double = 0.0,

    var gpsPointScreenValueDouble1: Double? = 0.0,
    var gpsPointScreenValueDouble2: Double? = 0.0,
    var gpsPointScreenValueDouble3: Double? = 0.0,
    var gpsPointScreenValue: Boolean? = false,
    var gpsPointScreenValueString: String? = "",
    var gpsPointScreenValueString2: String? = "",
    var gpsPointScreenValueString3: String? = "",
    var gpsPointScreenValueString4: String? = "",
    var gpsPointScreenValueBoolean: Boolean? = false,
    var gpsPointScreenValueLong: Long? = 0,
    var gpsPointScreenValueInt: Int? = 0
)
