package com.example.rideboard.utils

data class ScreenValues(
    val acceleration: Double = 0.0,
    val speed: Double = 0.0,
    val verticalSpeed: Double = 0.0,
    val direction: Double? = null,
    val directionString: String = "",
    val altitude: Double? = null,
    val minAltitude: Double? = null,
    val maxAltitude: Double? = null,
    val slope: Double = 0.0,
    val minSlope: Double = 0.0,
    val maxSlope: Double = 0.0,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val time: Long = 0,
    val gpsAltitudeAccuracy: Double = 299.9,
    val altitudeSourceMntMnsOrGps: String = "",
    val spreadAltitudeAndAltitudeGps: Double? = null,
    val coefficientOfSpreadAltitudeAndAltitudeGps: Double = 0.0,
    val durationAltitudeNotMnt: Int = 0,
    val isMoving: Boolean = false,
    val isStarted: Boolean = false,
    val cumulatedGpsPrecision: Double = 0.0,
    val isAltitudeGot: Boolean = false,
    val isGpsAltitudeGot: Boolean = false,
    val uncorrectedGpsAltitude: Double? = null,
    val displayedVerticalSpeed: Double = 0.0,
    val maxVerticalSpeed: Double = 0.0,
    val minVerticalSpeed: Double = 0.0,
    val displayedAltitude:Double? = null,
    val durationHighSpreadAltitude: Int = 0,

    val screenValueDouble1: Double? = 0.0,
    val screenValueDouble2: Double? = 0.0,
    val screenValueDouble3: Double? = 0.0,
    val screenValueBoolean: Boolean? = false,
    val screenValueString: String? = "",
    val screenValueString2: String? = "",
    val screenValueString3: String? = "",
    val screenValueString4: String? = "",
    val screenValueLong: Long? = 0,
    val screenValueInt: Int? = 0,


    val maxSpeed: Double = 0.0,
    val averageSpeed: Double = 0.0,
    val distance: Double = 0.0,
    val elevationGain: Double = 0.0,
    val durationSeconds: Long = 0L,
    val altMns: Double = 0.0,
    val altMnt: Double = 0.0,
    val altGps: Double = 0.0

)